name: Aggregated ORT

on:
  push:
    branches: [ "main" ]

jobs:
  ort:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: oss-review-toolkit/ort-ci-github-action@b6d71a83acba8619f16b30c008f212a7a572f8e8 #v1
        with:
          report-formats: CycloneDx,SpdxDocument,WebApp,PlainTextTemplate,Opossum
          run: 'cache-dependencies,cache-scan-results,labels,analyzer,evaluator,advisor,reporter,upload-results'
