name: Aggregated ORT

on: workflow_dispatch

jobs:
  ort:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          report-formats: CycloneDx,SpdxDocument,WebApp,PlainTextTemplate,Opossum
          run: 'cache-dependencies,cache-scan-results,labels,analyzer,evaluator,advisor,reporter,upload-results'
