name: Aggregated ORT

on: workflow_dispatch

jobs:
  ort:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: oss-review-toolkit/ort-ci-github-action@81698a977ebcf51bb3d6ef5c6a04220cf60d3bde
        with:
          report-formats: CycloneDx,SpdxDocument,WebApp,PlainTextTemplate,Opossum
          run: 'cache-dependencies,cache-scan-results,labels,analyzer,evaluator,advisor,reporter,upload-results'
