name: build

on:
  push:
    branches: [ "main" ]

jobs:
  ort:
    runs-on: ubuntu-latest
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      - name: Checkout project
        uses: actions/checkout@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: "gdi-ort-image:latest"
      - uses: oss-review-toolkit/ort-ci-github-action@b6d71a83acba8619f16b30c008f212a7a572f8e8 #v1
        with:
          image: gdi-ort-image:latest
          report-formats: CycloneDx,SpdxDocument,WebApp,PlainTextTemplate
          allow-dynamic-versions: 'true'
          fail-on: 'violations'